#!/usr/bin/env python3
"""
Generate the 60-slot rotation capture effects for historical data tracking.
Run this script to generate graphs_capture_effects.txt

Metrics tracked:
- gold: Current treasury
- stability: Current stability value
- population: Total country population
- manpower: Current manpower reserves
- monthly_income: Monthly trade + tax income
- tax_base: Total tax base (via script value)
"""

SLOTS = 60  # 5 years of monthly data

# Metrics: (variable_prefix, source_value, description)
METRICS = [
    ("gold", "gold", "Treasury"),
    ("stability", "stability", "Stability"),
    ("population", "total_population", "Population"),
    ("manpower", "manpower", "Manpower"),
    ("income", "monthly_income_trade_and_tax", "Monthly Income"),
    # For tax base, we'll use a custom approach since it may need special handling
    ("taxbase", "total_tax_base", "Tax Base"),
]


def generate_rotation(metric_name: str, source_value: str) -> str:
    """Generate the rotation code for one metric."""
    lines = []
    lines.append(f"    # === {metric_name.upper()} ===")

    # Rotate: shift all slots forward (59 <- 58, 58 <- 57, ..., 1 <- 0)
    for i in range(SLOTS - 1, 0, -1):
        lines.append(
            f"    set_variable = {{ name = {metric_name}_h_{i} value = var:{metric_name}_h_{i-1} }}"
        )

    # Capture current value in slot 0
    lines.append(f"    set_variable = {{ name = {metric_name}_h_0 value = {source_value} }}")
    lines.append("")

    return "\n".join(lines)


def generate_statistics(metric_name: str) -> str:
    """Generate statistics calculation for one metric."""
    lines = []
    lines.append(f"    # === {metric_name.upper()} STATISTICS ===")

    # Calculate sum for average
    lines.append(f"    set_variable = {{")
    lines.append(f"        name = {metric_name}_sum_60m")
    lines.append(f"        value = {{")
    lines.append(f"            value = 0")
    for i in range(SLOTS):
        lines.append(f"            add = var:{metric_name}_h_{i}")
    lines.append(f"        }}")
    lines.append(f"    }}")

    # Calculate average
    lines.append(f"    set_variable = {{")
    lines.append(f"        name = {metric_name}_avg_60m")
    lines.append(f"        value = {{")
    lines.append(f"            value = var:{metric_name}_sum_60m")
    lines.append(f"            divide = {SLOTS}")
    lines.append(f"        }}")
    lines.append(f"    }}")

    # Calculate change (current - oldest)
    lines.append(f"    set_variable = {{")
    lines.append(f"        name = {metric_name}_change_60m")
    lines.append(f"        value = {{")
    lines.append(f"            value = var:{metric_name}_h_0")
    lines.append(f"            subtract = var:{metric_name}_h_{SLOTS-1}")
    lines.append(f"        }}")
    lines.append(f"    }}")

    # Track min value
    lines.append(f"    set_variable = {{ name = {metric_name}_min_60m value = var:{metric_name}_h_0 }}")
    for i in range(1, SLOTS):
        lines.append(f"    if = {{ limit = {{ var:{metric_name}_h_{i} < var:{metric_name}_min_60m }} set_variable = {{ name = {metric_name}_min_60m value = var:{metric_name}_h_{i} }} }}")

    # Track max value
    lines.append(f"    set_variable = {{ name = {metric_name}_max_60m value = var:{metric_name}_h_0 }}")
    for i in range(1, SLOTS):
        lines.append(f"    if = {{ limit = {{ var:{metric_name}_h_{i} > var:{metric_name}_max_60m }} set_variable = {{ name = {metric_name}_max_60m value = var:{metric_name}_h_{i} }} }}")

    lines.append("")
    return "\n".join(lines)


def main():
    # Generate capture effect
    capture_output = []
    capture_output.append("# Auto-generated by generate_capture_effects.py")
    capture_output.append("# DO NOT EDIT MANUALLY - regenerate with the Python script")
    capture_output.append("")
    capture_output.append("capture_monthly_snapshot = {")

    for metric_name, source_value, description in METRICS:
        capture_output.append(generate_rotation(metric_name, source_value))

    # Update tracking metadata
    capture_output.append("    # === METADATA ===")
    capture_output.append("    change_variable = { name = graphs_months_tracked add = 1 }")
    capture_output.append("}")

    # Write capture effects
    with open("../common/scripted_effects/graphs_capture_effects.txt", "w", encoding="utf-8-sig") as f:
        f.write("\n".join(capture_output))

    print(f"Generated graphs_capture_effects.txt with {len(METRICS)} metrics x {SLOTS} slots")

    # Generate statistics effect
    stats_output = []
    stats_output.append("# Auto-generated by generate_capture_effects.py")
    stats_output.append("# DO NOT EDIT MANUALLY - regenerate with the Python script")
    stats_output.append("")
    stats_output.append("calculate_graph_statistics = {")

    for metric_name, source_value, description in METRICS:
        stats_output.append(generate_statistics(metric_name))

    stats_output.append("}")

    # Write statistics effects
    with open("../common/scripted_effects/graphs_statistics_effects.txt", "w", encoding="utf-8-sig") as f:
        f.write("\n".join(stats_output))

    print(f"Generated graphs_statistics_effects.txt")


if __name__ == "__main__":
    main()
